import React, {Suspense} from "react";
import GridBackground from "@/components/ui/grid-background";
import StoreNavbar from "@/app/store/components/store-navbar";
import {AuthDialogProvider} from "@/contexts/AuthDialogContext";
import {getCurrenUserDto} from "@/actions/auth";
import {cookies} from "next/headers";
import {tokenKeyString} from "@/lib/constants";
import Providers from "@/app/providers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {

  return (
    <>
      <Suspense fallback={<></>
        // <StoreNavbarSkeleton></StoreNavbarSkeleton>
      }>
        <StoreNavbar />
      </Suspense>

      {/*<GridBackground>*/}
        <div className="h-full
          px-6
          overflow-x-hidden
          md:px-8
          lg:px-16
          xl:px-44 flex w-full py-24 md:py-30 ">
          {children}
        </div>
      {/*</GridBackground>*/}
    </>
  )
}
