import React from "react";
import GridBackground from "@/components/ui/grid-background";
import StoreNavbar from "@/app/store/components/store-navbar";
import {AuthDialogProvider} from "@/contexts/AuthDialogContext";
import {getCurrentUser} from "@/actions/auth";
import {cookies} from "next/headers";
import {tokenKeyString} from "@/lib/constants";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {

  const token = cookies().get(tokenKeyString);
  const user = (await getCurrentUser(token?.value))?.data;
  return (
    <>
      <StoreNavbar user={user}/>
      <GridBackground>
        <div className="h-full
          px-6
          overflow-x-hidden
          md:px-8
          lg:px-16
          xl:px-44 flex w-full py-24 md:py-30 ">
          {children}
        </div>
      </GridBackground>
    </>
  )
}
