import type {Metadata} from "next";
import "./globals.css";
import {ThemeProvider} from "@/components/ThemeProvider";
import {TooltipProvider} from "@/components/ui/tooltip";
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem={true}
      storageKey="theme"
    >
      <TooltipProvider>
          {children}
      </TooltipProvider>
    </ThemeProvider>
    </body>
    </html>
  );
}
